### ISSUE TITLE
Watch History not shown after i run the script

### ISSUE THREAD

**Issue by krgchrs** [Jessime/youtube_history#6] opened 2017-12-21 10:41 UTC
Hi! I run the script which worked fine btw (apart from the wordcloud since i am using windows. After i run the script my watch history from youtube website disappeared! It shows only the videos i've watched after I used the script. Anyone had same issues??

**Comment by Jessime** [comment] 2017-12-21 14:33
Whoa, that’s crazy. Nobody else has mentioned anything like that happening. Just to not make any assumptions, have you restarted your browser/computer? 

Nothing about your watch history should change.

**Comment by krgchrs** [comment] 2018-01-02 12:57
Hello and happy new year! All of a sudden my watch history came back! And the funny part is that I didnt do anything! it just reappeared!So probably it was smth from my end

**Comment by Jessime** [comment] 2018-01-02 19:40
Weird. 

I'm going to go ahead and close this issue for now. But if you get any more insight into what happened, let me know!

**Closed as completed by Jessime** 2018-01-02 19:40 UTC

**Comment by wderousse** [comment] 2018-10-16 17:22
I can confirm this behavior. I ran this script yesterday and observed two things:

1.) My history in https://www.youtube.com/feed/history is fully intact.
2.) However every single "watched" indicator is now missing.

The biggest consequence is that the recommendations doesn't know I've watched anything even though many videos are in my history.

Do you drop use of credentials after downloading history? I wonder if the metadata download of each video is resetting this.

**Comment by Jessime** [comment] 2018-10-16 17:32
That seems a little different than what Chris experienced but still super weird. The only thing I use the credentials for is to pass them to `youtube-dl`, which does all the heavy lifting:

https://github.com/Jessime/youtube_history/blob/master/youtube_history.py#L127

Have you checked to see if there have been any similar complaints on their [Issues](https://github.com/rg3/youtube-dl/issues) page?

**Comment by wderousse** [comment] 2018-10-18 18:23
Yes I agree, after re-reading it is not the same issue. I didn't see anything obvious from youtube-dl page. Because history is intact I think that it is just the watched indicator/duration watched is what was lost. Without having evidence to support this it's like the videos were all loaded and then unloaded causing yt to record a "no view".
